version: '3'

services:
# MySQL
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: DOCKER123!
      MYSQL_DATABASE: default
      MYSQL_USER: docker
      MYSQL_PASSWORD: DOCKER123!
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - my_network

# FASTAPI
  fastapi:
    container_name: fastapi-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

# network definition
networks:
  my_network:
    driver: bridge