version: '3'

services:
# MySQL
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: DOCKER123!
      MYSQL_DATABASE: default
      MYSQL_USER: docker
      MYSQL_PASSWORD: DOCKER123!
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - docker_network

# Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-container
    ports:
    - "3000:3000"
    volumes:
        - ./grafana_data:/var/lib/grafana
        - ./configs/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    networks:
      - docker_network


# FASTAPI
  fastapi:
    container_name: fastapi-container
    build:
      context: .
      dockerfile: DockerfileFastAPI
    ports:
      - "8000:8000"
    networks:
        - docker_network
    depends_on:
      - mysql

# network definition
networks:
  docker_network:
    driver: bridge